### ISSUE TITLE
invalid dimensions

### ISSUE THREAD

**Issue by liyewu** [PINTO0309/HeadPoseEstimation-WHENet-yolov4-onnx-openvino#2]
I tried to transform keras model to onnx, and this is my code,
```
onnx_model = keras2onnx.convert_keras(self.model, self.model.name)
temp_model_file = './mymodel.onnx'
onnx.save_model(onnx_model, temp_model_file)
```
However, when I tried to run my onnx model, I got a crash and  error code is like this,
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input_1 for the following indices
 index: 1 Got: 3 Expected: 224
 index: 3 Got: 224 Expected: 3
 Please fix either the inputs or the model.
```
I also noticed your onnx model runs successfully, coud you please tell me how do you solve this problem?

**Comment by PINTO0309** [comment]
I've never used keras2onnx in the past because of its half-baked functionality.

https://github.com/PINTO0309/HeadPoseEstimation-WHENet-yolov4-onnx-openvino#2-reference

- whenet.py
  - Required: Python3.5
```python
        if snapshot!=None:
            self.model.load_weights(snapshot)

        for l in self.model.layers[1:]:
            l.trainable = False

        self.model.summary()
        self.model.save('model.h5')

        import tensorflow as tf
        from keras.models import load_model
        from keras import backend as K
        from tensorflow.python.framework import graph_io
        from tensorflow.python.framework import graph_util
        def freeze_graph(session, output, save_pb_dir='.', save_pb_name='frozen_model.pb', save_pb_as_text=False):
            graph = session.graph
            with graph.as_default():
                graphdef_inf = tf.graph_util.remove_training_nodes(graph.as_graph_def())
                graphdef_frozen = graph_util.convert_variables_to_constants(session, graphdef_inf, output)
                graph_io.write_graph(graphdef_frozen, save_pb_dir, save_pb_name, as_text=save_pb_as_text)
                return graphdef_frozen
        
        K.clear_session()
        K.set_learning_phase(0)
        model = load_model('model.h5')
        session = K.get_session()
        freeze_graph(session, [out.op.name for out in model.outputs], save_pb_dir='.')
```

- Python3.8
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/106_WHENet/convert_script.txt

**Comment by liyewu** [comment]
Thanks for your advise, it functions well!

**Comment by lailuboy** [comment]
> I tried to transform keras model to onnx, and this is my code,
> 
> ```
> onnx_model = keras2onnx.convert_keras(self.model, self.model.name)
> temp_model_file = './mymodel.onnx'
> onnx.save_model(onnx_model, temp_model_file)
> ```
> 
> However, when I tried to run my onnx model, I got a crash and error code is like this,
> 
> ```
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input_1 for the following indices
>  index: 1 Got: 3 Expected: 224
>  index: 3 Got: 224 Expected: 3
>  Please fix either the inputs or the model.
> ```
> 
> I also noticed your onnx model runs successfully, coud you please tell me how do you solve this problem?
 you can use transpose change input tensor，like this: input_frame = input_frame [:, :, ::-1].transpose([2,0,1])
