### ISSUE TITLE
any script to convert to trt with dynamic batch size?

### ISSUE THREAD

**Issue by thunder95** [PINTO0309/HeadPoseEstimation-WHENet-yolov4-onnx-openvino#3]

**Comment by PINTO0309** [comment]
Here.

Highly Recommended: https://github.com/PINTO0309/simple-onnx-processing-tools

https://github.com/PINTO0309/HeadPoseEstimation-WHENet-yolov4-onnx-openvino/blob/main/batchsize_clear.py

**Comment by thunder95** [comment]
thank you so much
