### ISSUE TITLE
yaw will output nan or inf after some infers with trt model

### ISSUE THREAD

**Issue by thunder95** [PINTO0309/HeadPoseEstimation-WHENet-yolov4-onnx-openvino#4]
Hello ,Sir,

I have tested, the input of network has no problem.
With one single image, this trt model infers with different results of yaw angle on different batches, while the roll and pitch keep the same.
When this model infers on webcam, the first almost ten batches are fully ok, but after that, the yaw results turn out inf or nan, while the roll and pitch also are ok.

This question might be somewhat too specific,  I would appreciate a lot if you can give me some hints about this. 

Thank you!

**Comment by PINTO0309** [comment]
Check directly with the researcher who designed the model.
https://github.com/Ascend-Research/HeadPoseEstimation-WHENet

**Comment by thunder95** [comment]
ok, understand
