### ISSUE TITLE
Datasets used for YOLOv4 head detection training

### ISSUE THREAD

**Issue by MarcoL29** [PINTO0309/HeadPoseEstimation-WHENet-yolov4-onnx-openvino#7]
Hello,

Was the YOLOv4 head detection model trained on the same datasets as YOLOv3 from [this repository](https://github.com/Ascend-Research/HeadPoseEstimation-WHENet), or were different datasets used?

Thank you!

**Comment by PINTO0309** [comment]
Yes. same. However, those datasets are of very low quality.
